version: '3.7'

services:
  redis:
    build: redis/
    network_mode: bridge
    links:
      - consul:consul
    expose:
      - 6379
      - 8500
  
  consul:
    image: consul:latest
    network_mode: bridge
    restart: always
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8400:8400"
    environment:
      - LOG_LEVEL=info
    command: "consul agent -server -bootstrap-expect=1 -data-dir=/consul/data -node=consul -client 0.0.0.0 -bind 0.0.0.0 -config-dir=/consul/config -dev -ui"
